# Generated by Django 3.2.4 on 2021-06-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=254)),
                ('artist', models.CharField(max_length=254)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=254, null=True)),
                ('highlight', models.BooleanField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
