# Generated by Django 3.2.4 on 2021-06-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='name',
        ),
    ]
