# Generated by Django 3.2.4 on 2021-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_title_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='AccessionYear',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Artist_Gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Artist_Prefix',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Artist_Role',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Artist_Suffix',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Constituent_ID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Culture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Is_Highlight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Repository',
        ),
        migrations.AddField(
            model_name='product',
            name='Object_Wikidata_URL',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags_AAT_URL',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags_Wikidata_URL',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='Credit_Line',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Dimensions',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Link_Resource',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
